Update partners.md
DIVD-NL/web-www pull request #58
Opened 2024-01-04 12:24 UTC by ChrisDIVD

2024-01-04 13:11 UTC, wschoot requested changes
Tikfoutje, maar kan 'm zelf niet aanpassen aangezien 'ie in je eigen repo is geforkt :)

2024-01-04 13:11 UTC, wschoot commented on partners.md
> +[Secura](https://www.secura.com) joined DIVDs new partnerporgram by providing annual funding
```suggestion
[Secura](https://www.secura.com) joined DIVDs new partnerprogram by providing annual funding
```

2024-01-08 09:04 UTC, MrSeccubus approved these changes
LGTM

2024-01-08 09:04 UTC, MrSeccubus commented
Merge je hem zelf @ChrisDIVD ?
(Of druk even op publish in de GUI van DecapCMS.)

2024-01-08 11:08 UTC, merged